/*
 * Created by french on 6/19/24.
*/
#ifndef GTKMIN_ROOT_CHILD_MAIN_CONTENT_H_
#define GTKMIN_ROOT_CHILD_MAIN_CONTENT_H_
#include "comm.h"
G_BEGIN_DECLS

G_END_DECLS
#endif  // GTKMIN_ROOT_CHILD_MAIN_CONTENT_H_
